### ISSUE TITLE
How Can I preditct a new image?

### ISSUE THREAD

**Issue by ncuxiaogang** [1adrianb/binary-face-alignment#8]
I have run your code with the samples under the floder /dataset/AFLW2000/ . But I find that each '.jpg' image file contains corresponding '.t7' file. But when I process a new image how can I generate '.t7' file. I have seen the 'utils.lua' under the 'binary-face-alignment/' directory, the corresponding '.t7' contains scale and center. What does it mean when I do face alignment?  I have no idea regarding the above. Thanks very much!

**Comment by RichardWenz** [comment]
What i understand from the code that 'center' and 'scale' are used to make the bounding box so they will predict according with the area of bounding box. If you check again the function of utils.bounding_box, you will see there are initialization of 'center' and 'scale'.

For .t7 i cannot certainly sure about my thought, but this is how i get it. Those .t7 files that existed are used to get information for landmark localization of each images in the dataset that provided (since that dataset is provided from another) and they used 68 points of landmark localization for the face alignment.

I hope my explanation could help you to understand how it works, because i also face the same problem as yours.

The easiest way to run the code with your own image is make new figure to display your own image and use similar gnuplot setup from original dataset. Then, adjust it (scale and center) according with your own images.

Best Regards.

**Comment by 1adrianb** [comment]
@ncuxiaogang The code doesn't directly support this as of this point but it should be straight forward to adapt it. The method expects a bounding box of the face based on which an aproximative scale and center of the face is computed. You can of course also directly try to supply the center and the scale.
I will be updating the code this month at some point to make it easier to run it on your own data.
